- user: name=smsapp state=present

- apt: name=git state=present
- apt: name=libmysql++-dev state=present
- apt: name=libpq-dev state=present
- apt: name=zlib1g state=present
- apt: name=libsasl2-dev state=present
- apt: name=libmemcached-dev state=present
- apt: name=libxml2-dev state=present
- apt: name=libxslt-dev state=present
- apt: name=python3-pip state=present

- name: Load source code
  git: "repo=https://github.com/wk-tech/crm-smsfly.git dest=/home/smsapp/repo accept_hostkey=yes"

- file: path=/home/smsapp/repo state=directory owner=smsapp recurse=yes

- file: path=/home/smsapp/repo state=directory owner='smsapp' group='smsapp'

- pip: name=virtualenv executable=pip3
- pip: requirements=/home/smsapp/repo/requirements.txt virtualenv=/home/smsapp/venv virtualenv_command=virtualenv virtualenv_python=python3

- name: Add env file
  template: 'src=smsapp.env dest=/home/smsapp/smsapp.env mode=0644'

- name: Add systemd unit
  template: 'src=unit.service dest=/etc/systemd/system/smsapp.service mode=0644'
  register: unit_added

- shell: systemctl daemon-reload
  when: unit_added|changed

- file: path=/home/smsapp/static state=directory owner=smsapp

- service: 'name=smsapp state=restarted enabled=yes'
